---
- name: Backup Cisco Switch Configuration
  hosts: SWITCH-2960
  gather_facts: false
  
  tasks:
    - name: Get running configuration from switch
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config_output
    
    - name: Save configuration to file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}_config_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.txt"
      delegate_to: localhost
    
    - name: Create backup directory if it doesn't exist
      file:
        path: ./backups
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true