---
- name: Backup Cisco Switch Configuration - Enhanced for DoD
  hosts: SWITCH-2960
  gather_facts: false
  vars:
    backup_dir: "/home/admin/Switch_Configs/{{ inventory_hostname }}"
    rhel_username: "{{ OS_USERNAME }}"
    rhel_password: "{{ OS_PASSWORD }}"
  
  tasks:
      
    - name: Ensure Switch_Configs base directory exists
      file:
        path: /home/admin/Switch_Configs
        state: directory
        owner: admin
        group: admin
        mode: '0755'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
      run_once: true
    
    - name: Create backup directory structure on rhel-demo
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: admin
        group: admin
        mode: '0750'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
      run_once: true
    
    - name: Gather switch information
      cisco.ios.ios_facts:
        gather_subset:
          - hardware
          - interfaces
          - config
      register: switch_facts
    
    - name: Get running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
          - show version
          - show inventory
          - show ip interface brief
      register: config_data
    
    - name: Save running configuration
      copy:
        content: "{{ config_data.stdout[0] }}"
        dest: "{{ backup_dir }}/running-config.txt"
        mode: '0640'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
    
    - name: Save version information
      copy:
        content: "{{ config_data.stdout[1] }}"
        dest: "{{ backup_dir }}/version_info.txt"
        mode: '0640'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
    
    - name: Save inventory information
      copy:
        content: "{{ config_data.stdout[2] }}"
        dest: "{{ backup_dir }}/inventory.txt"
        mode: '0640'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
    
    - name: Save interface status
      copy:
        content: "{{ config_data.stdout[3] }}"
        dest: "{{ backup_dir }}/interface_status.txt"
        mode: '0640'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
    
    - name: Create backup summary
      copy:
        content: |
          Backup Summary for {{ inventory_hostname }}
          ==========================================
          Backup Date: {{ backup_datetime }}
          Device Type: {{ switch_facts.ansible_facts.ansible_net_model | default('Unknown') }}
          Serial Number: {{ switch_facts.ansible_facts.ansible_net_serialnum | default('Unknown') }}
          IOS Version: {{ switch_facts.ansible_facts.ansible_net_version | default('Unknown') }}
          
          Files Backed Up:
          - running-config.txt
          - version_info.txt
          - inventory.txt
          - interface_status.txt
        dest: "{{ backup_dir }}/backup_summary.txt"
        mode: '0640'
      delegate_to: rhel-demo
      vars:
        ansible_user: "{{ rhel_username }}"
        ansible_password: "{{ rhel_password }}"
        ansible_become: true
    
    - name: Log backup completion
      debug:
        msg: "Configuration backup completed for {{ inventory_hostname }} at {{ backup_datetime }}"
