---
- name: Cisco Catalyst Center auth smoke test
  hosts: localhost
  gather_facts: false

  vars:
    catalyst_center:
      host: "pnpserver.cvn9001.navy.mil"
      username: "adm.canes"
      password: "!Q@W3e4r!Q@W#e4r"
      validate_certs: false        # set true with ca_path if you trust the DNAC CA
      ca_path: null                # e.g. "/etc/pki/ca-trust/source/anchors/dnac-ca.pem"
      timeout: 30

  tasks:
    - name: Get API token
      ansible.builtin.uri:
        url: "https://{{ catalyst_center.host }}/dna/system/api/v1/auth/token"
        method: POST
        url_username: "{{ catalyst_center.username }}"
        url_password: "{{ catalyst_center.password }}"
        force_basic_auth: true
        headers:
          Accept: "application/json"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        ca_path: "{{ catalyst_center.ca_path | default(omit) }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: 200
        return_content: true
        use_proxy: no
        use_netrc: no
      register: auth
      no_log: true

    - name: Extract token
      ansible.builtin.set_fact:
        dnac_token: "{{ auth.json.Token | default(auth.json.token) | default(auth.json.accessToken) }}"
      no_log: true

    - name: Assert token present
      ansible.builtin.assert:
        that:
          - dnac_token is string
          - dnac_token | length > 0
        fail_msg: "Auth succeeded but no token field returned."

    - name: Prove auth by calling /version
      ansible.builtin.uri:
        url: "https://{{ catalyst_center.host }}/dna/system/api/v1/version"
        method: GET
        headers:
          Accept: "application/json"
          X-Auth-Token: "{{ dnac_token }}"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        ca_path: "{{ catalyst_center.ca_path | default(omit) }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: 200
        return_content: true
        use_proxy: no
        use_netrc: no
      register: ver

    - name: Auth OK
      ansible.builtin.debug:
        msg: "Authenticated. Catalyst Center version: {{ ver.json.version | default('unknown') }}"
