---
- name: Cisco Catalyst Center Inventory Demo
  hosts: localhost
  gather_facts: false
  vars:
    catalyst_center:
      host: "pnpserver.cvn9001.navy.mil"
      username: "adm.canes"
      password: "!Q@W3e4r!Q@W#e4r"
      validate_certs: false
      timeout: 30

  # minimal facts for timestamps only
  pre_tasks:
    - name: Collect minimal facts for time only
      setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'date_time'

    - name: Preflight - resolve and TCP check
      wait_for:
        host: "{{ catalyst_center.host }}"
        port: 443
        timeout: 5
      register: tcp_check
      failed_when: not tcp_check.elapsed is defined
      changed_when: false

  tasks:
    - name: Get authentication token from Catalyst Center
      uri:
        url: "https://{{ catalyst_center.host }}/dna/system/api/v1/auth/token"
        method: POST
        # Prefer Ansible's basic auth path over hand-rolled header
        url_username: "{{ catalyst_center.username }}"
        url_password: "{{ catalyst_center.password }}"
        force_basic_auth: true
        headers:
          Accept: "application/json"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: 200
        return_content: true
      register: auth_response
      no_log: false  # do not print creds or token

    - name: Extract auth token (handle casing differences)
      set_fact:
        auth_token: >-
          {{ auth_response.json.Token
             | default(auth_response.json.token)
             | default(auth_response.json.accessToken)
             | default(auth_response.json.AccessToken)
          }}
      no_log: false

    - name: Fail early if no token parsed
      assert:
        that:
          - auth_token is string
          - auth_token | length > 0
        fail_msg: "Authentication succeeded but token not found in response. Enable temporary debugging to inspect auth_response."

    - name: Get device inventory (first page)
      uri:
        url: "https://{{ catalyst_center.host }}/dna/intent/api/v1/network-device?offset=1&limit=500"
        method: GET
        headers:
          Accept: "application/json"
          X-Auth-Token: "{{ auth_token }}"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: 200
      register: inventory_response

    - name: Normalize device list
      set_fact:
        devices: >-
          {{ (inventory_response.json.response
              | default(inventory_response.json.devices)
              | default([])) }}

    - name: Get site information
      uri:
        url: "https://{{ catalyst_center.host }}/dna/intent/api/v1/site"
        method: GET
        headers:
          Accept: "application/json"
          X-Auth-Token: "{{ auth_token }}"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: 200
      register: sites_response
      failed_when: false

    - name: Normalize site list
      set_fact:
        sites: "{{ sites_response.json.response | default([]) }}"

    - name: Get network health summary (most platforms require timestamp in ms)
      vars:
        ts_ms: "{{ (ansible_date_time.epoch | int) * 1000 }}"
      uri:
        url: "https://{{ catalyst_center.host }}/dna/intent/api/v1/network-health?timestamp={{ ts_ms }}"
        method: GET
        headers:
          Accept: "application/json"
          X-Auth-Token: "{{ auth_token }}"
        validate_certs: "{{ catalyst_center.validate_certs }}"
        timeout: "{{ catalyst_center.timeout }}"
        status_code: [200, 404]
      register: health_response
      failed_when: false

    - name: Inventory summary
      debug:
        msg: |
          ===========================================
          CISCO CATALYST CENTER INVENTORY SUMMARY
          ===========================================
          Total Devices: {{ devices | length }}
          Server: {{ catalyst_center.host }}
          Retrieved at: {{ ansible_date_time.iso8601 }}
          ===========================================

    - name: Detailed device info
      debug:
        msg: |
          Device {{ idx + 1 }}:
          - Hostname: {{ item.hostname | default('N/A') }}
          - Management IP: {{ item.managementIpAddress | default('N/A') }}
          - Device Type: {{ item.type | default('N/A') }}
          - Platform: {{ item.platformId | default('N/A') }}
          - Software Version: {{ item.softwareVersion | default('N/A') }}
          - Serial Number: {{ item.serialNumber | default('N/A') }}
          - MAC Address: {{ item.macAddress | default('N/A') }}
          - Role: {{ item.role | default('N/A') }}
          - Reachability: {{ item.reachabilityStatus | default('N/A') }}
          - Last Updated: {{ item.lastUpdated | default('N/A') }}
          ---
      loop: "{{ devices }}"
      loop_control:
        index_var: idx
      when: devices | length > 0

    - name: Site summary
      debug:
        msg: |
          ===========================================
          SITE INFORMATION
          ===========================================
          Total Sites: {{ sites | length }}
      when: sites | length > 0

    - name: Site details (defensive parsing)
      debug:
        msg: |
          Site {{ idx + 1 }}:
          - Name: {{ item.name | default('N/A') }}
          - Site ID: {{ item.id | default('N/A') }}
          - Type: {{ (item.additionalInfo | default([]) | first).attributes.type | default('N/A') }}
          - Address: {{ (item.additionalInfo | default([]) | first).attributes.address | default('N/A') }}
          ---
      loop: "{{ sites }}"
      loop_control:
        index_var: idx
      when: sites | length > 0

    - name: Network health summary
      debug:
        msg: |
          ===========================================
          NETWORK HEALTH SUMMARY
          ===========================================
          Health Score: {{ health_response.json.response[0].healthScore | default('N/A') }}%
          Total Count: {{ health_response.json.response[0].totalCount | default('N/A') }}
          Good Count: {{ health_response.json.response[0].goodCount | default('N/A') }}
          Fair Count: {{ health_response.json.response[0].fairCount | default('N/A') }}
          Poor Count: {{ health_response.json.response[0].poorCount | default('N/A') }}
          ===========================================
      when:
        - health_response.status == 200
        - health_response.json.response is defined
        - health_response.json.response | length > 0

    - name: Create inventory report file
      copy:
        content: |
          # Cisco Catalyst Center Inventory Report
          Generated: {{ ansible_date_time.iso8601 }}
          Server: {{ catalyst_center.host }}

          ## Device Summary
          Total Devices: {{ devices | length }}

          ## Device Details
          {% for device in devices %}
          ### Device {{ loop.index }}
          - **Hostname:** {{ device.hostname | default('N/A') }}
          - **Management IP:** {{ device.managementIpAddress | default('N/A') }}
          - **Device Type:** {{ device.type | default('N/A') }}
          - **Platform:** {{ device.platformId | default('N/A') }}
          - **Software Version:** {{ device.softwareVersion | default('N/A') }}
          - **Serial Number:** {{ device.serialNumber | default('N/A') }}
          - **Role:** {{ device.role | default('N/A') }}
          - **Reachability:** {{ device.reachabilityStatus | default('N/A') }}
          {% endfor %}

          ## Site Summary
          Total Sites: {{ sites | length }}

          {% if health_response.status == 200 and health_response.json.response is defined %}
          ## Network Health
          - **Health Score:** {{ health_response.json.response[0].healthScore | default('N/A') }}%
          - **Total Devices:** {{ health_response.json.response[0].totalCount | default('N/A') }}
          - **Good:** {{ health_response.json.response[0].goodCount | default('N/A') }}
          - **Fair:** {{ health_response.json.response[0].fairCount | default('N/A') }}
          - **Poor:** {{ health_response.json.response[0].poorCount | default('N/A') }}
          {% endif %}
        dest: "./catalyst_center_inventory_report.md"
      when: devices | length > 0

    - name: Display completion message
      debug:
        msg: |
          ===========================================
          DEMO COMPLETED SUCCESSFULLY!
          ===========================================
          ✓ Connected to Catalyst Center: {{ catalyst_center.host }}
          ✓ Retrieved device inventory
          ✓ Retrieved site information
          ✓ Retrieved network health data
          ✓ Generated report: catalyst_center_inventory_report.md
          ===========================================
